export const LOAD_SKATER_CARDS = 'LOAD_SKATER_CARDS';
export const LOAD_MOVE_CARDS = 'LOAD_MOVE_CARDS';
export const LOAD_OPPONENT_SKATER_CARD = 'LOAD_OPPONENT_SKATER_CARD';
export const SELECT_SKATER_CARD = 'SELECT_SKATER_CARD';