// TODO: clean this up!
export const LOAD_ALL_SKATER_CARDS = 'LOAD_ALL_SKATER_CARDS';
export const LOAD_SKATER_CARDS = 'LOAD_SKATER_CARDS';
export const LOAD_MOVE_CARDS = 'LOAD_MOVE_CARDS';
export const LOAD_OPPONENT_SKATER_CARD = 'LOAD_OPPONENT_SKATER_CARD';
export const SELECT_SKATER_CARD = 'SELECT_SKATER_CARD';
export const SELECT_SKATER_CARD2 = 'SELECT_SKATER_CARD2';
export const INCREMENT_YOUR_SCORE = 'INCREMENT_YOUR_SCORE';
export const INCREMENT_OPPONENT_SCORE = 'INCREMENT_OPPONENT_SCORE';
export const SET_TURN_IN_PROGRESS = 'SET_TURN_IN_PROGRESS';
export const RESET_SELECTED_SKATER_CARD = 'RESET_SELECTED_SKATER_CARD';
export const RESET_OPPONENT_SKATER_CARD = 'RESET_OPPONENT_SKATER_CARD';
export const SET_GAME_OVER = 'SET_GAME_OVER';
export const RESET_GAME_SCORE = 'RESET_GAME_SCORE';
export const LOAD_SKATER_DECK = 'LOAD_SKATER_DECK';
export const LOAD_OPPONENT_SKATER_DECK = 'LOAD_OPPONENT_SKATER_DECK';
export const INCREMENT_TURN = 'INCREMENT_TURN';
export const REMOVE_OPPONENT_SKATER_FROM_DECK = 'REMOVE_OPPONENT_SKATER_FROM_DECK';

// My Cards Screen
export const SELECT_MYCARDS_SKATER = 'SELECT_MYCARDS_SKATER';

// Training
export const SET_POTENTIAL_TRAINING_SKATERS = 'SET_POTENTIAL_TRAINING_SKATERS';
export const SET_TRAINING_SKATER_LIST = 'SET_TRAINING_SKATER_LIST';

// Picks
export const SET_PICKS = 'SET_PICKS';